Azure cis benchmark v1.3.0
JupiterOne/security-policy-templates pull request #87
Opened 2021-02-23 21:37 UTC by ndowmon

I split this into two commits, so it's easier to see the difference between v1.1.0 and v1.3.0. 

This is going to be used for some upcoming work in accelerating that development of the `graph-azure` project.

Please refer to the Azure CIS Benchmark v1.3.0 when reviewing: https://downloads.cisecurity.org/#/

2021-02-23 22:07 UTC, a-u-h-g requested changes

2021-02-23 22:07 UTC, a-u-h-g commented on templates/standards/cis-azure-foundations/v1.3.0.json
> +          "ref": "4.17",
Extra requirement - 4.17 should be removed

2021-02-23 22:07 UTC, a-u-h-g commented on templates/standards/cis-azure-foundations/v1.3.0.json
> +          "title": "Ensure that multi-factor authentication is enabled for all nonprivileged users (Manual)",
non-privileged*

2021-02-23 23:19 UTC, ndowmon commented
Thanks @a-u-h-g for the attention to detail. Fixed the two issues you identified.

2021-02-24 14:58 UTC, a-u-h-g approved these changes

2021-02-24 14:58 UTC, merged